### ISSUE TITLE
Could we get some usage instructions?

### ISSUE THREAD

**Issue by apbarratt** [Paneon/php-to-typescript#4]
I can't see how I'm actually meant to configure this to work.

I've run `composer require paneon/php-to-typescript`

And I've added a script to my composer.json:

```
"generate-DTOs": [
    "php bin/console typescript:generate"
]
```

And I've added `@TypeScriptInterface` to a class in my code.

But when I then run `composer run-script generate-DTOs` I'm told `There are no commands defined in the "typescript" namespace.`

I'm a frontend guy myself so PHP is not my strong point, I'm just trying to figure out how to get a bunch of interfaces the doctrine files our backend folk have put together :)

**Comment by Macavity** [comment]
@apbarratt You can run composer scripts using `composer run generate-DTOs` based on your example.
That should essentially be enough 😄
